const userNames = [
  'Theo',
  'Geo',
  'Burrito',
  'Tito',
  'Guito',
  'Tea',
  'Me',
  'OG',
  'Pickle Slick',
  'Tommy Bohammy',
  'Tarzan',
  'Larz',
  'Snoozy',
  'Andy',
  'Randy',
  'Josie',
  'Rosie',
  'Fembot',
  'Mojo',
  'Hugh',
  'Jaynus',
  'Obi',
  'Won',
  'Todd',
  'May',
  'Sephoroth',
  'Cloud',
  'Aries',
  'Mack',
  'Wes',
  'Lord Ben',
  'Dover',
  'Semper',
  'Angel',
  'Grim',
  'Elmo',
  'Kyle',
  'Chad',
  'Susan',
  'Karen',
  'Bey',
  '117',
  'Bit',
  'Xavier',
  'Zidane',
  'Niyam',
  'Grenadine',
  'Zion',
  'Ishmail',
  'Kenny',
  'Stan',
  'Butters',
  'Eric',
  'Talmadge',
  'Henry',
  'Diana',
  'Ruth',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Bonaparte',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const randomThought = [
  'Why is my cat so annoying',
  'She said quickly but i thought she said quicky',
  'Still wondering how i can learn from this assignment',
  'Deez Nuckle Sandwitches',
  'I stood 10 feet tall on top of my pancake stack',
  'Can someone please bring me some syrup',
  'Ill eat a shoe if they ever make Top Gun 2',
  'Hello cat...',
  'I uninstalled this app yesterday, why is it still here.',
  'Bored, feelin cute, I might eat a pizza later.',
  'Cache me on the DM',
  'I sent my grandma a picture the other day by mistake. I meant to send it to my girlfriends grandma.',
  'What direction should I go now?',
  'Did you hear about that fox that was on fire?',
  'Not Running sucks - Nike',
  'Life is like a box of chocolate infused gummy bears, you never know what your gonna get.',
  'I didnt mean to poke her with my umbrelle. Does she still have her eye?',
  'I ordered food from Door Sprint.',
];

const getRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomName = () =>
  `${getRandomName(userNames)} ${getRandomName(userNames)}`;

const getRandomThoughts = (int) => {
  const results = [];
  for (let i = 0; i < int; i++) {
    results.push({
      thought: getRandom(randomThought),
      score: Math.floor(Math.random() * (99 - 70 + 1) + 70),
    });
  }
  return results;
};
t
module.exports = { getRandomName, getRandomThoughts };
